debugMode: false
#General parameters
minStartVotes: 2
prestartTimer: 60
spawnRadius: 250
spawnDistance: 240
alertRadius: 50
alertTimeout: 60
hideVictimNametagAbovePlayers: 4
enablePotionHandicap: true
enableStartInventory: true
#Escape the Wall gamemode
enableEscapeGamemode: false
#Wall generator performance
blocksPerSecondLimit: 100000
#Escape gamemode parameters
playzoneSize: 1000
wallThickness: 8
spotSize: 4
groundSpotQty: 3
airSpotQty: 2
undergroundSpotQty: 5
#Start inventory
startInventory:
  OAK_LOG: 3
  COOKIE: 3