#General parameters
minVotestarters: 1
votestartTimer: 60
spawnRadius: 250
spawnDistance: 240
alertRadius: 50
alertTimeout: 60
#gamemode
enableEscapeGamemode: false
#escape gamemode parameters
playzoneSize: 1000
wallThickness: 10
spotSize: 8
groundSpotDensity: 3
airSpotDensity: 2
undergroundSpotDensity: 5
allowBuildWall: false