name: ClassD
version: 0.3
description: Manhunt
author: sooslick
main: ru.sooslick.outlaw.Engine
api-version: 1.16
commands:
  outlaw:
    description: some outlaw commands
    usage: /outlaw <commands>
  y:
    description: alias for /outlaw accept command
    usage: /y