######## CORE ########
#More console output
debugMode: false
#Block filler performance
blocksPerSecondLimit: 100000

#Selected gamemode from gamemodes list
preferredGamemode: any%
#Available gamemodes and their java classes. Modify this list only if you know what are you doing
gamemodes:
  any%: ru.sooslick.outlaw.gamemode.anypercent.AnyPercentBase
  wall: ru.sooslick.outlaw.gamemode.wall.WallGameModeBase
  evacuation: ru.sooslick.outlaw.gamemode.evacuation.EvacuationBase

#### CORE GAMEPLAY ####
#Lobby parameters
minStartVotes: 2
prestartTimer: 60
printEndgameStatistics: true

#Startgame parameters
spawnRadius: 250
spawnDistance: 240
hideVictimNametagAboveHunters: 2
enablePotionHandicap: true
enableStartInventory: true

#Gameplay parameters
alertRadius: 50
alertTimeout: 60
friendlyFireEnabled: true
denyNetherTravelling: false
#Allowed values for compassUpdates (case insensitive): Always, OnClick, Never
compassUpdates: ALWAYS
compassUpdatesPeriod: 1
enableVictimGlowing: false
milkGlowImmunityDuration: 180

#Start inventory
victimStartInventory:
  OAK_LOG: 3
  COOKIE: 3

hunterStartInventory:
  OAK_LOG: 2
  COOKIE: 2

####### THE WALL & EVACUATION ##########
#Common
playzoneSize: 1000

#Escape the Wall parameters
wallThickness: 8
spotSize: 4
groundSpotQty: 3
airSpotQty: 2
undergroundSpotQty: 5

#Evacuation stages
waitTime: 720
landingTime: 600
cordonTime: 300
cordonZoneSize: 16
endGameAfterCordon: true